version: '3.8'

services:
  nginx:
    build: ./nginx
    image: registry.hosted-domains.com/shane/static-site-nginx:${VERSION}
    env_file: ${ENV_FILE}
    deploy:
      replicas: 1
    volumes:
      - data_dir:/data
    secrets:
      - source: cssnr.com.crt
        target: /etc/ssl/cssnr.com.crt
      - source: cssnr.com.key
        target: /etc/ssl/cssnr.com.key
    ports:
      - "${DOCKER_PORT}:443"

  bash-sftp:
    image: registry.hosted-domains.com/public/bash-sftp:latest
    env_file: ${ENV_FILE}
    deploy:
      replicas: 1
    volumes:
      - data_dir:/data
    ports:
      - "${FTP_PORT}:2222"

#  ftpd_server:
#    image: stilliard/pure-ftpd
#    env_file: ${ENV_FILE}
#    deploy:
#      replicas: 1
#    volumes:
#      - data_dir:/data
#    ports:
#      - "${FTP_PORT}:21"
#      - "${FTP_PASV}:${FTP_PASV}"
#    environment:
#      FTP_USER_HOME: /data/html
#      PUBLICHOST: "swarm.hosted-domains.com"

  php-fpm:
    image: php:7.2-fpm-alpine
    env_file: ${ENV_FILE}
    deploy:
      replicas: 1
    volumes:
      - data_dir:/data

secrets:
  cssnr.com.crt:
    external: true
  cssnr.com.key:
    external: true

volumes:
  data_dir:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${NFS_HOST},rw"
      device: ":${NFS_DIRECTORY}"
